import json

demo = ('access_token', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJjaGVud2VuemhlIiwic2NvcGUiOlsiYWxsIl0sImNsaWVudCI6IkFQUCIsImV4cCI6MTcxMTAwOTk1NywiYXV0aG9yaXRpZXMiOlsiQURNSU5JU1RSQVRPUiJdLCJqdGkiOiJjVE1Jc0pmemFBWHc0dUUxZ1ZiOS0yWFBUeGMiLCJjbGllbnRfaWQiOiJQTVMiLCJzdGF0dXMiOjIwMH0.pyecPRTV_BdAs_qOEq3kQBdtNK7IER4peFlrecCmLu8')

print(demo[0])