# Generated by Selenium IDE
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.firefox.service import Service
import pytest
from selenium.webdriver.common.by import By
from common.web_common.chrome_option import ChromeOptions
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.service import Service
from webdriver_manager.firefox import GeckoDriverManager


class TestXiugaichandao():
    def setup_method(self, method):
        service = Service(GeckoDriverManager().install())
        # 初始化 Firefox WebDriver
        self.driver = webdriver.Firefox(service=service)
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    @pytest.mark.selen
    def test_xiugaichandao(self):
        self.driver.get("http://192.168.2.210:83/my-index.html?tid=kv4bh3yo")
        self.driver.set_window_size(1480, 967)
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(6) .text").click()
        self.driver.switch_to.frame(1)
        self.driver.find_element(By.LINK_TEXT, "聊天自研").click()
        self.driver.find_element(By.LINK_TEXT, "Bug").click()
        self.driver.find_element(By.ID, "bysearchTab").click()
        self.driver.find_element(By.ID, "value1").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#field1_chosen b")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "#field1_chosen .chosen-search")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.LINK_TEXT, "Bug标题").click()
        self.driver.find_element(By.CSS_SELECTOR, ".active-result:nth-child(2)").click()
        self.driver.find_element(By.ID, "pk_value1-search").click()
        self.driver.find_element(By.ID, "pk_value1-item-479-option").click()
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) .btn:nth-child(4)").click()
        element = self.driver.find_element(By.CSS_SELECTOR, "#module_chosen span")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()
        element = self.driver.find_element(By.CSS_SELECTOR, "#module_chosen input")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()
        self.driver.find_element(By.LINK_TEXT, "/群聊").click()
        self.driver.find_element(By.CSS_SELECTOR, ".active-result:nth-child(4)").click()
        self.driver.find_element(By.ID, "submit").click()
        self.driver.find_element(By.LINK_TEXT, "返回").click()
